### ISSUE TITLE
URLs and email addresses written incorrectly

### ISSUE THREAD

**Issue by omahlama** [alias-rahil/handwritten.js#10]
Http url:
![http URL](https://user-images.githubusercontent.com/1110213/90630252-58d34a00-e229-11ea-9db4-4ec5ca4cb097.png)

Email address:
![email address](https://user-images.githubusercontent.com/1110213/90630293-6d174700-e229-11ea-90e3-5dfb7e17d117.png)

As you can see in the images, there is an extra space after the dot in these cases, even though it doesn't exist in the source document.

**Comment by alias-rahil** [comment]
Should be fixed in 17.0.0
