### ISSUE TITLE
Use PNG for the screenshot instead of JPEG

### ISSUE THREAD

**Issue by lipis** [alias-rahil/handwritten.js#12]
JPEG for text is not the best: https://github.com/alias-rahil/handwritten.js/blob/master/screenshots/lorem-ipsum.jpeg

**Comment by alias-rahil** [comment]
Thanks. Done!

**Comment by lipis** [comment]
Still JPEG: https://github.com/alias-rahil/handwritten.js/tree/master/screenshots

**Comment by alias-rahil** [comment]
Hi @lipis. Changing the file name will break the url to the image and I have linked the raw image url to many places. Instead I increased the quality of image. That should do it.
