### ISSUE TITLE
Support ruled pages: lines between text

### ISSUE THREAD

**Issue by KhushrajRathod** [alias-rahil/handwritten.js#17]
**Describe the solution you'd like**
My school expects us to write on ruled paper :( 
Is it possible to support ruled pages?

Something like:
![Ruled paper](https://cdn.vertex42.com/WordTemplates/images/printable-lined-paper-wide-ruled.png)

Thanks!

**Comment by alias-rahil** [comment]
Hi @KhushrajRathod! The blue underline looked very unnatural so I went with black underline for the text. Haven't added the left margin yet, might do later (will have to rewrite some logic of the code). Try the 17.0.0 with with ruled: true (see docs) and let me know if that is satisfactory. Awaiting reply to close the issue.

**Comment by KhushrajRathod** [comment]
> Hi @KhushrajRathod! The blue underline looked very unnatural so I went with black underline for the text. Haven't added the left margin yet, might do later (will have to rewrite some logic of the code). Try the 17.0.0 version with with ruled: true (see [docs](https://github.com/alias-rahil/handwritten.js/blob/master/README.md)) and let me know if that is satisfactory. Awaiting reply to close the issue.

Nice. Works as expected.
Thanks!

**Comment by alias-rahil** [comment]
:)
