### ISSUE TITLE
Talking about new language

### ISSUE THREAD

**Issue by ronaldohoch** [alias-rahil/handwritten.js#18]
Hello!

I've read the CONTRIBUTING.md and i'm here to talk about add PT-br font, how can i made it?

**Comment by alias-rahil** [comment]
Hello @ronaldohoch - I have borrowed the English handwriting from [GDGVIT/HandWriter](https://github.com/GDGVIT/HandWriter). The process of creating the handwriting dataset is simple but very tiresome. You will have to write each letter correctly, spatially arranged in a grid, extract each letter using python's OpenCV (or some other method you are comfortable with). Clean the images and save it's png or jpeg buffer value in [src/dataset.json](https://github.com/alias-rahil/handwritten.js/blob/master/src/dataset.json). Modify [src/index.js](https://github.com/alias-rahil/handwritten.js/blob/master/src/index.js) (wraptext function) accordingly.


More on creating the handwriting dataset [here](https://saurusxi.github.io/HandwritingParser/generating_hashes).

**Comment by alias-rahil** [comment]
PRs for adding support for new languages are welcome!
