### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by hsrambo07** [alias-rahil/handwritten.js#28]
UI improvement needed to the current website.

Feature requested : Better UI for the site 
Submit your proposed design screenshot first..
Do it such that it wont break the code. :)

proposed changes: a minimalistic approroach to the website

**Comment by hsrambo07** [comment]
Please assign me this issue.. I would like to work on it

**Comment by hsrambo07** [comment]
Thanks

**Comment by alias-rahil** [comment]
There is already a website built, but sure if you wanna work on it or make it better, make a PR, i'll review.

**Comment by hsrambo07** [comment]
Hey, i want to keep updating this website with better designs ahead, so can u add me as a contributor.

**Comment by alias-rahil** [comment]
Sure!

**Comment by hsrambo07** [comment]
Thanks

**Comment by alias-rahil** [comment]
@all-contributors please add @hsrambo07  for code and maintenance

**Comment by alias-rahil** [comment]
done in https://github.com/alias-rahil/handwritten.js/pull/29

**Comment by hsrambo07** [comment]
Thankss @alias-rahil 
💯 :)
