### ISSUE TITLE
Hello World test generates pdf document with 2 pages

### ISSUE THREAD

**Issue by faizanu94** [alias-rahil/handwritten.js#3]
Nice library, I tried running a sample [Hello World](https://github.com/alias-rahil/handwritten.js#usage) test. It produces 2 pages in **output.pdf** document, however expected pages should be 1. Code for reproducing the issue:

```
const handwritten = require('./src/index.js');
const fs = require('fs');
(async function(text) {
    let converted = await handwritten(text);
    converted.pipe(fs.createWriteStream('output.pdf'));
})("Hello, world!");
```

**Comment by alias-rahil** [comment]
Fixed in [this](https://github.com/alias-rahil/handwritten.js/commit/0b6562534b7d67d13b4c023a22b1b050b1a02314) commit. Upgrade to version 16.7.0.
