### ISSUE TITLE
Add workflow to publish automatically when there is a version change

### ISSUE THREAD

**Issue by alias-rahil** [alias-rahil/handwritten.js#39]
Currently, there is no CI/CD pipeline implemented for the npm library. It would be great to have a pipeline which checks for version change in `package.json` file and publish a newer version if there is a change. It should run on `master` branch.

**Comment by ashikka** [comment]
@alias-rahil Could you assign this issue to me?

**Comment by alias-rahil** [comment]
> @alias-rahil Could you assign this issue to me?

Yeah, sure thing.

**Comment by alias-rahil** [comment]
@all-contributors please add @ashikka for code
