### ISSUE TITLE
Problem with french

### ISSUE THREAD

**Issue by Vadiml1024** [alias-rahil/handwritten.js#4]
It has proble with french language: all accentuetés character are rendered without accents

**Comment by m0narch** [comment]
There is no dataset for accentued character, i will make the character image today if i can  and upload them :p

**Comment by alias-rahil** [comment]
handwritten.js only supports English letters. The conversion of other language characters to their most equivalent English character was deliberate to partially support other languages. It is always better to have something than nothing. I am not planning to add support for other languages for now. I will merge pull requests if any, for this issue.
