### ISSUE TITLE
add tests and git hooks (husky)

### ISSUE THREAD

**Issue by alias-rahil** [alias-rahil/handwritten.js#40]
Currently we have no proper checks for code formatting and functional tests.

To-do:
* Write tests using jest or mocha (just check if the exported function executes properly without any errors)
* Add pre-commit hooks to run eslint and the tests
* (Optional) Add commit-msg hook to follow proper commit message convection. See: https://www.conventionalcommits.org/en/v1.0.0/

**Comment by ashikka** [comment]
@alias-rahil  Can you assign this issue to me?

**Comment by alias-rahil** [comment]
@all-contributors please add @ashikka for maintenance
