### ISSUE TITLE
Ability to change ink color

### ISSUE THREAD

**Issue by SuyashSonawane** [alias-rahil/handwritten.js#46]
**Is your feature request related to a problem? Please describe.**
Currently there is no option to change ink color

**Describe the solution you'd like**
Pass hex value or use predefined constants to change ink color

**Additional context**
I went through the source code and found a way to implement this feature, I would like to contribute it 🚀

I have attached the results below

> handwritten(rawtext, { ruled: true, inkColor: '#0000FF' }).then((converted) => {
>     converted.pipe(fs.createWriteStream('output.pdf'))
> })

![image](https://user-images.githubusercontent.com/35629339/131224244-d364672e-58bf-494a-800c-15bddbe37413.png)

**Comment by alias-rahil** [comment]
Looks awesome, thanks for your interest in this project. I assigned the issue to you
