### ISSUE TITLE
outputtype option type

### ISSUE THREAD

**Issue by newtonmunene99** [alias-rahil/handwritten.js#57]
**Describe the bug**
The `outputtype` option doesn't work because when validating with Joi in `checkArgType` function in `src/index`, the option validated is `outputType` but in `main`, `outputtype` is used.

**To Reproduce**

```js
import handwritten from "handwritten.js";

async function handwrite() {
  const result = await handwritten("some sample text", {
    outputtype: "png/b64",
  });
}
```

The above throws an error that `outputtype` is not allowed.

```js
import handwritten from "handwritten.js";

async function handwrite() {
  const result = await handwritten("some sample text", {
    outputType: "png/b64",
  });
}
```

The above works but the output type will still end up being a PDF/PDFKit instance

**Expected behavior**
```js
import handwritten from "handwritten.js";

async function handwrite() {
  const result = await handwritten("some sample text", {
    outputType: "png/b64",
  });
}
```

The above should output a png base64

**Screenshots**

![Screenshot from 2021-12-03 14-42-31](https://user-images.githubusercontent.com/29271333/144597016-578f500f-60f8-4683-bfd2-551cf20fb047.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome
 - Version: ^18.11.0

**Additional context**

**Comment by alias-rahil** [comment]
@all-contributors please add @newtonmunene99 for bug report and code

**Comment by tbukfrc** [comment]
I'm reopening this bug, because it still occurs in the browser-based version of the library.

**Comment by alias-rahil** [comment]
@tbukfrc should be fixed now. Feel free to reopen if the issue persists
