### ISSUE TITLE
Need documention for adding to webpack/yarn 

### ISSUE THREAD

**Issue by sadiqmmm** [alias-rahil/handwritten.js#6]
Hi
This library looks really awesome. I have a Rails application and want to use handwritten.js. 
Can you please improve your docs to installation/setup for webpack/yarn.
Thanks

**Comment by alias-rahil** [comment]
I don't have experience with using npm packages in browser. Perhaps someone could help me with that. Contributions are welcome.

**Comment by MrBenJ** [comment]
Hey @alias-rahil - I might be able to help out here. I could make a small demo site while I'm at it. Getting better at Node.js streams is something that's been on my list of stuff to learn and I think this could be a win-win scenario for both of us. Feel free to assign this to me if you're OK with me taking a crack at this :)

**Comment by alias-rahil** [comment]
Thank you @MrBenJ, appreciate your contribution.

**Comment by alias-rahil** [comment]
Thank you @MrBenJ, contributions are much appreciated.

> I could make a small demo site while I'm at it.
That would be great! I went ahead and assigned the issue #8 to you as well. Thanks!

**Comment by MrBenJ** [comment]
@alias-rahil - Yes! Go for it. I've already forked the repo and I'm building a small React front end for this. I'm not a designer so it'll probably look like a cat threw up some HTML and CSS, but I'll do what I can :)

**Comment by alias-rahil** [comment]
Hi again @MrBenJ . Can you leave a comment on the issue #8 so that I can assign it to you? An issue can only be assigned to commenters or collaborators  of the repo (I didn't know this but now it makes 100% sense) XD

**Comment by alias-rahil** [comment]
> @alias-rahil - Yes! Go for it. I've already forked the repo and I'm building a small React front end for this. I'm not a designer so it'll probably look like a cat threw up some HTML and CSS, but I'll do what I can :)

Since there is no progress, I have opened it for contribution for hacktoberfest and unassgned you. Let me know if you are still interested in working :)

**Comment by MrBenJ** [comment]
Hey @alias-rahil - sorry. I had some stuff come up with work. I was planning on having this be my first PR for this hacktoberfest. I can make sure I ship it and make the PR on October 1st for you.

Sorry for not keeping you up to date on this!

**Comment by alias-rahil** [comment]
Re-assigned!

**Comment by alias-rahil** [comment]
The package is not compatible with webpack. Closing it.
