### ISSUE TITLE
demo website

### ISSUE THREAD

**Issue by pannous** [alias-rahil/handwritten.js#8]
Hi I can't find a demo website showing off handwritten.js ; should be easy with github pages?

**Comment by alias-rahil** [comment]
assigning to @MrBenJ

**Comment by MrBenJ** [comment]
Hey @alias-rahil ! I'm working on this now on my own fork at the moment :)

**Comment by alias-rahil** [comment]
> Hey @alias-rahil ! I'm working on this now on my own fork at the moment :)

Since there is no progress, I have opened it for contribution for hacktoberfest and unassgned you. Let me know if you are still interested in working :)

**Comment by alias-rahil** [comment]
Re-assigned!

**Comment by MrBenJ** [comment]
Hey @alias-rahil - I had some trouble getting your project to bundle for webpack and browser environments. It looks like the code isn't quite optimized for a web environment at the moment.

I saw your site that you put together and I think what I'll do right now is just do some nice styling and get it looking pretty to help people out.

I spent a couple of hours today just trying to get the project bundled in via webpack, but unfortunately, it's seems that the code is meant for more for a Node.js environment. I saw your separate JS file with `handwritten` as a global, so I'm going to use that as a base and go from there.

Needless to say, I've committed to helping out your project and giving you a cool and nice site to help people use your project, so I'm going to honor that commitment and get something nice out for you within a day or 2!

**Comment by alias-rahil** [comment]
> I saw your site that you put together and I think what I'll do right now is just do some nice styling and get it looking pretty to help people out.

Thanks man, I can't even express how excited I am to merge your contribution xD. The current website looks ugly. Just a nice frontend will do!

> 
> I spent a couple of hours today just trying to get the project bundled in via webpack, but unfortunately, it's seems that the code is meant for more for a Node.js environment. I saw your separate JS file with `handwritten` as a global, so I'm going to use that as a base and go from there.

That file is bundled using browserify. You can build on the current demo-site if you want. Add styling and make it look not ugly.

> 
> Needless to say, I've committed to helping out your project and giving you a cool and nice site to help people use your project, so I'm going to honor that commitment and get something nice out for you within a day or 2!

Thanks for your commitment. Take your time building it. Thanks a lot!!!

**Comment by alias-rahil** [comment]
Also @MrBenJ can you re-fork the repo please? I did a full rebase of git history because I had accidentally made some of my commits without configuring git locally.

**Comment by MrBenJ** [comment]
Sure thing! I will refork and move the code over. I think what you have with the demo website isn't bad, it just need some HTML + CSS TLC :). I'm on it!

**Comment by alias-rahil** [comment]
Done in #25, thanks @MrBenJ.
