### ISSUE TITLE
My output seems distored/skewed

### ISSUE THREAD

**Issue by domvo** [alias-rahil/handwritten.js#9]
[output.pdf](https://github.com/alias-rahil/handwritten.js/files/5095604/output.pdf)

Somehow it looks weird, as in stretched/skewed, especially compared to the example. The code I', using is just the hello world example with another text.

OS: MacOS 10.15.5
Node: 12.16.1 LTS

**Comment by alias-rahil** [comment]
Thanks for bringing it to my notice. Should be fixed now. Update to 16.8.0.
